post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWRjZjQ4NjBiYWJhZTUxOTBkMGZlNjE0IiwiaWF0IjoxNTc0MTA5NTYzfQ.x5JJM-HbZrO-YQ2yiQ6h02eNtuhZyaHdzXkHr2CkEHE

{
  "title": "Testing Authorization",
  "author": "Hellas",
  "url": "ohmygawds.com",
  "likes": 0,
  "user": "5dcf4860babae5190d0fe614"
}