post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGxhcyIsImlkIjoiNWRjZjQ4NjBiYWJhZTUxOTBkMGZlNjE0IiwiaWF0IjoxNTc0MTA2NzYyfQ.azCF_fIJtgWZsFicnTROn2fOa18RMpnuMYrYZsDVSu0

{
  "title": "Nani world",
  "author": "Allas Jane",
  "url": "https://tastytreats.wordpress.com/",
  "likes": 300
}